#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; PORT="$2"

if [[ -f "$DOKKU_ROOT/VHOST" ]]; then
  VHOST=$(< "$DOKKU_ROOT/VHOST")
  SUBDOMAIN=${APP/%\.${VHOST}/}
  if [[ "$APP" == *.* ]] && [[ "$SUBDOMAIN" == "$APP" ]]; then
    location="/"
    hostname="${APP/\//-}"
  else
    hostname="$VHOST/${APP/\//-}"
    location="/${APP/\//-}"
  fi

  cat<<EOF > $DOKKU_ROOT/$APP/nginx_location.conf

  location    $location {
    proxy_pass  http://$APP;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-For \$remote_addr;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Request-Start \$msec;
  }

EOF

  cat<<EOF > $DOKKU_ROOT/$APP/nginx_upstream.conf

  upstream $APP { server 127.0.0.1:$PORT; }

EOF

echo "http://$hostname" > "$DOKKU_ROOT/$APP/URL"
pluginhook nginx-pre-reload $APP
sudo /etc/init.d/nginx reload > /dev/null
fi
